texture.colortex3.format=RGBA8
texture.colortex3.clear=true


screen = <empty> <profile> <empty> [SHADOWS] [LIGHTING] iScream uScream weAllScream forIceCream *
screen.SHADOWS = shadowMapResolution shadowFilter
screen.LIGHTING = SSAO SSR

screen.columns = 3
screen.SHADOWS.columns = 2

profile.LOW  = !SSAO ShadowType=1 SSR:false !program.composite2
profile.MED  =  SSAO ShadowType=2 SSR:false !program.composite2
profile.HIGH =  SSAO ShadowType=3 SSR:true

sliders = iScream uScream weAllScream forIceCream